language: cpp
python:
  - 3.8
  
install:
  - pip3 --version
  - pip3 install --user conan cmake
  

jobs:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      env:
        - MACOSX_DEPLOYMENT_TARGET=10.14
        - PATH="${HOME}/Library/Python/3.7/bin:${PATH}"
        - MATRIX_EVAL=""
    - os: linux
      dist: bionic
      compiler: gcc
      before_install: 
        - pyenv global 3.8
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # I couldn't get ${GCC_VER} in here successfully
            - gcc-9
            - g++-9
            - doxygen
            - python3
            - python3.8
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
    - os: linux
      dist: bionic
      compiler: clang
      before_install: 
        - pyenv global 3.8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
      addons: { apt: { packages: ['doxygen', 'clang-8'] } }


before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j2
  - ctest -j2
